#!/usr/bin/env bash
# generate-workflow.sh — Emit .github/workflows/deploy.yml from coolify.yaml.
# Implements GHCR same-image promotion. Smoke test is the gate: staging pass → auto-promote to prod.
#
# build.context and build.dockerfile are read from coolify.yaml.
# Defaults: context = '.' (repo root), dockerfile = './Dockerfile'.
# For nested-app repos (e.g. ai-upskilling/skillmap), set build.context in coolify.yaml (e.g. ./skillmap).
#
# IMPORTANT — no env-specific --build-arg is passed.
# The whole point of same-image promotion is that staging and production run the
# IDENTICAL image bytes (same SHA tag). Baking NEXT_PUBLIC_BASE_URL (or any other
# env-specific value) at build time would require separate builds per environment,
# defeating the model. Instead, all env-specific values are injected at container
# startup by Coolify via the Doppler-managed DOPPLER_TOKEN. The Dockerfile keeps
# ARG NEXT_PUBLIC_BASE_URL="" with an empty default for forward-compat, but this
# generator deliberately omits it from the build-args.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib-coolify-api.sh"

YAML_PATH="${1:-./coolify.yaml}"
[ -f "$YAML_PATH" ] || { echo "ERROR: $YAML_PATH not found" >&2; exit 1; }

# Determine the output path — relative to the directory containing coolify.yaml
OUT_DIR="$(cd "$(dirname "$YAML_PATH")" && pwd)/.github/workflows"
OUT_PATH="$OUT_DIR/deploy.yml"

eval "$(python3 -c "
import yaml
d=yaml.safe_load(open('$YAML_PATH'))
print(f\"PROJECT='{d.get('project','')}'\")
print(f\"SERVER_ALIAS='{d.get('server','')}'\")
print(f\"REGISTRY_IMAGE='{d.get('registry',{}).get('image','')}'\")
print(f\"RETENTION='{d.get('registry',{}).get('retention_tags',5)}'\")
print(f\"STAGING_DOMAIN='{d.get('environments',{}).get('staging',{}).get('domain','')}'\")
print(f\"PROD_DOMAIN='{d.get('environments',{}).get('production',{}).get('domain','')}'\")
print(f\"BUILD_CONTEXT='{d.get('build',{}).get('context','.')}'\"  )
print(f\"BUILD_DOCKERFILE='{d.get('build',{}).get('dockerfile','./Dockerfile')}'\"  )
staging = d.get('coolify_app_ids',{}).get('staging') or ''
prod = d.get('coolify_app_ids',{}).get('production') or ''
print(f\"STAGING_APP_UUID='{staging}'\")
print(f\"PROD_APP_UUID='{prod}'\")
")"

# When called from init.sh (before /setup-coolify provisioning), app IDs are null (~).
# Use placeholder strings so the workflow file is still generated; the actual UUIDs
# and COOLIFY_URL will be embedded when /setup-coolify (provision) regenerates this file.
NEEDS_PROVISION=false
if [ -z "$STAGING_APP_UUID" ] || [ -z "$PROD_APP_UUID" ]; then
  NEEDS_PROVISION=true
  STAGING_APP_UUID="${STAGING_APP_UUID:-REPLACE_WITH_COOLIFY_APP_ID_STAGING}"
  PROD_APP_UUID="${PROD_APP_UUID:-REPLACE_WITH_COOLIFY_APP_ID_PRODUCTION}"
  echo "INFO: coolify_app_ids not yet set — workflow will contain placeholder UUIDs." >&2
  echo "      Run /setup-coolify (provision) after setting up Doppler to replace them." >&2
fi

if [ "$NEEDS_PROVISION" = "false" ]; then
  coolify_load_server "$SERVER_ALIAS"   # sets COOLIFY_URL
else
  # No coolify.json available yet (or app IDs not provisioned) — use placeholder URL.
  COOLIFY_URL="https://REPLACE_WITH_YOUR_COOLIFY_URL"
fi

# GHCR owner and package name from registry image path
OWNER=$(echo "$REGISTRY_IMAGE" | awk -F'/' '{print $2}')
PACKAGE=$(echo "$REGISTRY_IMAGE" | awk -F'/' '{print $3}')

mkdir -p "$OUT_DIR"

cat > "$OUT_PATH" << YAML
# Auto-generated by ~/.claude/skills/setup-coolify/scripts/generate-workflow.sh
# Source: $YAML_PATH
# Pattern: GHCR same-image promotion. Smoke test is the gate — no manual approval.
# Do not hand-edit — regenerate via /setup-coolify (rerun) instead.
#
# NOTE: NEXT_PUBLIC_BASE_URL (and any other env-specific value) is intentionally
# NOT passed as a --build-arg. Same-image promotion requires identical image bytes
# across staging and production; env-specific values flow through DOPPLER_TOKEN at
# container startup. See skillmap/Dockerfile for the rationale.
name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: \${{ steps.tag.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v4
      - id: tag
        run: echo "short_sha=\${GITHUB_SHA:0:7}" >> \$GITHUB_OUTPUT
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: $BUILD_CONTEXT
          file: $BUILD_DOCKERFILE
          push: true
          tags: $REGISTRY_IMAGE:\${{ steps.tag.outputs.short_sha }}
          # No build-args — same image, runtime env injection via Doppler.

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    env:
      COOLIFY_API_KEY: \${{ secrets.COOLIFY_API_KEY }}
      COOLIFY_URL: $COOLIFY_URL
      STAGING_APP_UUID: $STAGING_APP_UUID
      TAG: \${{ needs.build.outputs.tag }}
      STAGING_DOMAIN: $STAGING_DOMAIN
    steps:
      - name: Set image tag on staging app
        run: |
          curl -sfS -X PATCH "\$COOLIFY_URL/api/v1/applications/\$STAGING_APP_UUID" \\
            -H "Authorization: Bearer \$COOLIFY_API_KEY" \\
            -H "Content-Type: application/json" \\
            -d "{\\"docker_registry_image_tag\\":\\"\$TAG\\"}"
      - name: Trigger staging deploy
        run: |
          curl -sfS "\$COOLIFY_URL/api/v1/deploy?uuid=\$STAGING_APP_UUID&force=false" \\
            -H "Authorization: Bearer \$COOLIFY_API_KEY"
      - name: Smoke test staging (max 6 min)
        run: |
          for i in \$(seq 1 12); do
            sleep 30
            if curl -sfS "https://\$STAGING_DOMAIN/" -o /dev/null; then
              echo "Staging healthy on attempt \$i"; exit 0
            fi
            echo "Wait \$i/12 ..."
          done
          echo "Staging did not respond within 6min" >&2; exit 1

  deploy-production:
    needs: [smoke-staging, build]
    runs-on: ubuntu-latest
    env:
      COOLIFY_API_KEY: \${{ secrets.COOLIFY_API_KEY }}
      COOLIFY_URL: $COOLIFY_URL
      PROD_APP_UUID: $PROD_APP_UUID
      TAG: \${{ needs.build.outputs.tag }}
    steps:
      - name: Set same image tag on production app (no rebuild)
        run: |
          curl -sfS -X PATCH "\$COOLIFY_URL/api/v1/applications/\$PROD_APP_UUID" \\
            -H "Authorization: Bearer \$COOLIFY_API_KEY" \\
            -H "Content-Type: application/json" \\
            -d "{\\"docker_registry_image_tag\\":\\"\$TAG\\"}"
      - name: Trigger production deploy
        run: |
          curl -sfS "\$COOLIFY_URL/api/v1/deploy?uuid=\$PROD_APP_UUID&force=false" \\
            -H "Authorization: Bearer \$COOLIFY_API_KEY"

  ghcr-cleanup:
    needs: deploy-production
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Keep last $RETENTION GHCR tags
        uses: actions/delete-package-versions@v5
        with:
          package-name: $PACKAGE
          package-type: container
          min-versions-to-keep: $RETENTION
YAML

# Validate output is parseable YAML
python3 -c "import yaml; yaml.safe_load(open('$OUT_PATH'))" >/dev/null

# Defensive: ensure no NEXT_PUBLIC_BASE_URL appears as a build-arg (same-image promotion guarantee)
if grep -qE 'NEXT_PUBLIC_BASE_URL\s*=' "$OUT_PATH" 2>/dev/null; then
  if grep -nE 'NEXT_PUBLIC_BASE_URL' "$OUT_PATH" | grep -vE '^[0-9]+:\s*#' >/dev/null 2>&1; then
    echo "ERROR: generated workflow references NEXT_PUBLIC_BASE_URL outside of a comment — this breaks same-image promotion." >&2
    exit 1
  fi
fi

echo "WROTE $OUT_PATH"
echo "  build context: $BUILD_CONTEXT  dockerfile: $BUILD_DOCKERFILE"
echo "  build: ghcr.io tag = commit short SHA (NO build-args — runtime env via Doppler)"
echo "  deploy-staging: same tag -> staging app $STAGING_APP_UUID"
echo "  deploy-production: SAME tag -> production app $PROD_APP_UUID (auto after staging smoke test)"
echo "  ghcr-cleanup: keep last $RETENTION tags of $PACKAGE"
